#!/bin/sh

set -eu

if [ "$#" -ne 1 ]; then
    echo "usage: $0 <output-directory>" >&2
    exit 64
fi

_output_directory=$1
_output_file=$_output_directory/Versions.generated.swift
_git=$(command -v git 2>/dev/null) || {
    echo "error: git was not found" >&2
    exit 1
}

mkdir -p "$_output_directory"

if [ -n "${VG_VERSION:-}" ]; then
    _tag=$VG_VERSION
else
    _tag=$("$_git" describe --tags --exact-match 2>/dev/null) || _tag=
fi

if [ -n "${VG_COMMIT:-}" ]; then
    _commit=$VG_COMMIT
else
    _commit=$("$_git" rev-parse HEAD 2>/dev/null) || _commit=
fi

_contains() {
    case $1 in
        *"$2"*) return 0 ;;
        *) return 1 ;;
    esac
}

_quote() {
    _quote_value=$1
    _quote_hashes=
    while _contains "$_quote_value" "${_quote_hashes}\"" \
        || _contains "$_quote_value" "\"${_quote_hashes}" \
        || _contains "$_quote_value" "\\${_quote_hashes}"
    do
        _quote_hashes=${_quote_hashes}#
    done
    printf '%s"%s"%s' "$_quote_hashes" "$_quote_value" "$_quote_hashes"
}

_temporary_file=$(mktemp "${_output_file}.XXXXXX")
trap 'rm -f "$_temporary_file"' EXIT HUP INT TERM

{
    cat <<'EOF'
// Generated by VersionsGeneratorPlugin. Do not edit.

internal enum Versions {

EOF
    printf '    internal static nonisolated let tag: String = '
    _quote "$_tag"
    printf '\n    internal static nonisolated let commit: String = '
    _quote "$_commit"
    printf '\n}\n'
} > "$_temporary_file"

mv "$_temporary_file" "$_output_file"
trap - EXIT HUP INT TERM
